import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./NavBar";
import Footer from "./Footer";
import { StoreProvider } from "./store/StoreProvider";
import AuthProviders from "./api/auth/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProviders>
          <StoreProvider>
            <nav className="fixed top-0 left-0 w-full z-50">
              <NavBar />
            </nav>
            <main className="pt-22">{children}</main>
            <footer>
              <Footer />
            </footer>
          </StoreProvider>
        </AuthProviders>
      </body>
    </html>
  );
}
